name: format

on: [push]

jobs:
    ayanami:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: denoland/setup-deno@main
              with:
                deno-version: "1.9.2"
            - name: Run fmt
              run: |
                deno fmt
            - name: Git setting
              run: |
                git config --local user.emal kazkichi0906@gmail.com
                git config --local user.name FukeKazki
            - name: Commit files
              run: |
                if (git diff --shortstat | grep '[0-9]'); then \
                    git add .; \
                    git commit -m "Automation: format file"; \
                    git push; \
                fi
