name: format

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        step:
            - uses: actions/checkout@master
            - uses: denoland/setup-deno@main
              with:
                deno-version: "1.9.2"
            - name: Run fmt
              run: |
                deno fmt
            - name: Git setting
              run: |
                git config --local user.emal kazkichi0906@gmail.com
                git config --local user.name FukeKazki
            - name: Commit files
              run: |
                git add .
                git commit -m "Automation: format file"
                git push origin master